name: Build

on: [push, pull_request]

jobs:
  build-x11:
    name: Linux (X11)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make SYSTEM=X
    - uses: actions/upload-artifact@v3
      with:
        name: arcem-x11
        path: ./arcem

  build-msvc:
    name: Windows (MSVC ${{ matrix.msvc.platform }})
    runs-on: windows-latest

    strategy:
      matrix:
        msvc:
        - { platform: Win32, artifact: vc/Release/ArcEm.exe }
        - { platform: x64, artifact: vc/x64/Release/ArcEm.exe }

    steps:
    - name: Set up msbuild
      uses: microsoft/setup-msbuild@v1.1.3
    - uses: actions/checkout@v3
    - name: Build
      run: msbuild vc/ArcEm.sln /m /p:BuildInParallel=true /p:Configuration=Release /p:Platform=${{ matrix.msvc.platform }}
    - uses: actions/upload-artifact@v3
      with:
        name: arcem-msvc-${{ matrix.msvc.platform }}
        path: ${{ matrix.msvc.artifact }}

  build-mingw:
    name: Windows (${{ matrix.mingw.msystem }})
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        mingw:
        - { msystem: mingw32, msys-env: mingw-w64-i686 }
        - { msystem: mingw64, msys-env: mingw-w64-x86_64 }

    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.mingw.msystem }}
        install: ${{ matrix.mingw.msys-env }}-cc make
    - uses: actions/checkout@v3
    - name: Build
      run: make SYSTEM=win
    - uses: actions/upload-artifact@v3
      with:
        name: arcem-${{ matrix.mingw.msystem }}
        path: ./ArcEm.exe

  build-watcom:
    name: Windows (OpenWatcom)
    runs-on: ubuntu-latest

    steps:
    - name: Set up OpenWatcom
      uses: open-watcom/setup-watcom@v0
      with:
        tag: 2021-12-01-Build
    - uses: actions/checkout@v3
    - name: Build
      run: wmake -f Makefile.ow
    - uses: actions/upload-artifact@v3
      with:
        name: arcem-watcom
        path: ./ArcEm.exe

  build-riscos:
    name: RISC OS
    runs-on: ubuntu-latest
    container: riscosdotinfo/riscos-gccsdk-4.7:latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make SYSTEM=riscos-single CROSS=arm-unknown-riscos-
    - uses: actions/upload-artifact@v3
      with:
        name: arcem-riscos
        path: ./ArcEm

  build-amiga:
    name: ${{ matrix.amiga.name }}
    runs-on: ubuntu-latest
    container: amigadev/crosstools:${{ matrix.amiga.host }}

    strategy:
      matrix:
        amiga:
        # - { name: "AmigaOS 3", host: "m68k-amigaos", system: "amigaos3" }
        - { name: "AmigaOS 4", host: "ppc-amigaos", system: "amiga" }

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make SYSTEM=${{ matrix.amiga.system }} CROSS=${{ matrix.amiga.host }}-
    - uses: actions/upload-artifact@v3
      with:
        name: arcem-${{ matrix.amiga.host }}
        path: ./arcem
